import Head from "next/head";
import Image from "next/image";
import HomePage from "./home";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Portifolio de Axel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
      <h1 className="text-3xl font-bold underline bg-red-500">Hello world!</h1>
    </div>
  );
};

export default Home;
